services:
  db:
    image: postgres:16
    container_name: transcoding_database
    restart: always
    environment:
      POSTGRES_USER: rshdhere
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: transcoding_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
